language: android
sudo: required
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.1
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository # for design library
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

notifications:
  email: false

before_install:
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager "platforms;android-28"
  - export EMULATOR="system-images;android-21;google_apis;armeabi-v7a" # Used to install/create emulator
  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid warning
