language: android
sudo: required
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.1
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository # for design library
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager "platforms;android-28"