language: android
sudo: required
jdk: oraclejdk8
android: null
components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
    - 'yes | sdkmanager "platforms;android-27"'
    - 'yes | sdkmanager "platforms;android-28"'
